# This one uses Lightly library with different Training Framework (TiCO)
model_name: CLTSim2
gpu_device_ids: [1]
batch_size: 1024
dataset_class: SimpleCellDataset
city: porto
seed: 123
state_dict_path: models/states/porto/cltsim2.pt
epochs: 40
debug: False
early_stopping: False
val_sample_size: 10000
model_args:
  city: porto
  model_files_path: models/token_embs/cell/ #models/baselines/trajcl_files
  dataset_cell_file: porto_cell100_cellspace.pkl
  embs_file: porto_cell_embs_node2vec256.pkl #porto_cell100_embs128.pkl
  emb_size: 256
  learning_rate: 0.0001
  weight_decay: 0.0001
  cellroad_emb_dim: 256 #256
  cell_embedding_dim: 256 #256
  moco_nqueue: 2048 
  moco_temperature: 0.05

