model_name: TIGR
gpu_device_ids: [0]
batch_size: 128 #32
dataset_class: TIGRDataset
city: porto
seed: 123
val_sample_size: 10000
state_dict_path: models/states/porto/tigr/model.pt            
#train_epochs: 1
epochs: 10
debug: False
early_stopping: False
model_args:
  epochs: 10
  batch_size: 512 
  learning_rate: 0.001
  n_layers: 2
  emb_size: 512 
  road_emb1_size: 64 
  road_emb2_size: 128
  cell_emb_size: 256
  time_emb_size: 64
  # Training
  moco_nqueue: 2048 
  moco_temperature: 0.05
  # Masking
  view1: [trim, cut] # mask, trim, cutout
  view2: [mask, trim, cut] # mask, trim, cutout
  aug_prob: 0.85
  mask_prob: 0.85
  cut_prob: 0.85
  trim_prob: 0.865
  mask_ratio: 0.3
  cut_ratio: 0.3
  trim_ratio: 0.3
  # road
  dytraffic_embs_path: models/token_embs/road/porto_sfc24_64.pt
  road_emb_path2: models/token_embs/road/porto_road_embs_traj_skipgram.pkl 
  #cell
  dataset_cell_file: porto_cell100_cellspace.pkl
  cell_embs_file: porto_cell_embs_node2vec256.pkl
  model_files_path: models/token_embs/cell/
  #time
  time_emb_path: models/token_embs/time/
  time2vec_path: models/states/other/d2v_32_9833_5.760072401186963.pth