name: Destination
task: DestinationTask
city: porto
seed: 123
gpu_device_ids: [0]
task_args:
  metrics: [["accuracy", {}], ["f1_macro", {"average": "macro"}], ["top_k_accuracy", {"k": 5, "normalize": true}]]
  learning_rate: 0.001
batch_size: 128
dataset_class: DestinationDataset
sample_size: 400000
epochs: 10
early_stopping: False
monitor_metric: accuracy
mode: max
min_delta: 0.002
patience: 5
debug: False